---
- name: Add dynamic hosts from JSON survey
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Parse hosts configuration
      set_fact:
        hosts_config: "{{ survey_hosts_config }}"

    - name: Add hosts to inventory
      add_host:
        name: "{{ item.host }}"
        groups: survey_targets
        ansible_user: "{{ item.user }}"
        ansible_password: "{{ item.password }}"
      loop: "{{ hosts_config }}"

- name: Perform tasks on the dynamically added hosts
  hosts: survey_targets
  tasks:
    - name: ping test
      ping: